### ISSUE TITLE
hash_tree_root of merkleization.nim cannot be compiled

### ISSUE THREAD

**Issue by jangko** [status-im/nim-ssz-serialization#64] opened 2023-08-22 13:25 UTC
```nim
import
  unittest2,
  stew/byteutils,
  ../ssz_serialization/merkleization

type
  Eth2Digest = object
    data: array[32, byte]

  ExecutionAddress = object
    data: array[20, byte]

  BloomLogs = object
    data: array[256, byte]

  UInt256 = object
    data: array[32, byte]

  ExecutionPayload* = object
    # Execution block header fields
    parent_hash*: Eth2Digest
    fee_recipient*: ExecutionAddress
      ## 'beneficiary' in the yellow paper
    state_root*: Eth2Digest
    receipts_root*: Eth2Digest
    logs_bloom*: BloomLogs
    prev_randao*: Eth2Digest
      ## 'difficulty' in the yellow paper
    block_number*: uint64
      ## 'number' in the yellow paper
    gas_limit*: uint64
    gas_used*: uint64
    timestamp*: uint64
    extra_data*: List[byte, 32]
    base_fee_per_gas*: UInt256

    # Extra payload fields
    block_hash*: Eth2Digest
      ## Hash of execution block

proc main() =
  var h: ExecutionPayload
  let z = hash_tree_root(h)

main()
```

error message:
```text
F:\projects\nim-ssz-serialization\tests\test_hast_tree_root.nim(43, 25) template/generic instantiation of `hash_tree_root` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(1294, 22) template/generic instantiation of `hashTreeRootAux` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(804, 20) template/generic instantiation of `merkleizeFields` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(805, 8) template/generic instantiation of `enumerateSubFields` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(565, 17) template/generic instantiation of `addChunkDirect` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(566, 27) template/generic instantiation of `hash_tree_root` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(1294, 22) template/generic instantiation of `hashTreeRootAux` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(804, 20) template/generic instantiation of `merkleizeFields` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(805, 8) template/generic instantiation of `enumerateSubFields` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(565, 17) template/generic instantiation of `addChunkDirect` from here
F:\projects\nim-ssz-serialization\ssz_serialization\merkleization.nim(201, 15) Error: attempting to call undeclared routine: 'combineChunks'
```

maybe missing mixin or export marker.

**Comment by tersec** [comment] 2023-08-23 02:12
Can't reproduce based on what you describe. Tried three things:

- `rm ~/.nimble/ -r && nimble install ssz_serialization` [to pull in all the Nimble dependencies; probably there's a better way] using Nim 1.6.14, and modified only the import line of your code to `import ... ssz_serialization/merkleization` instead of `import ... ../ssz_serialization/merkleization`. This compiled fine.

- Then, made a fresh git clone of `nim-ssz-serialization` at commit d24c719ebfd53f5c606177ac760446692abbb056 and put verbatim the code you posted into `nim-ssz-serialization` where the paths lined up correctly. This also compiled fine.

- I know this isn't what you're saying happens here, but I've seen cases where there was some quirk of `nimbus-eth2`'s build environment creates build failures which don't exist outside of that. So I did basically the second thing, but within the vendored copy of `nim-ssz-serialization` in `nimbus-eth2/vendor/nim-ssz-serialization`. Also builds fine.

**Comment by jangko** [comment] 2023-08-23 04:24
Hmm, it's a Nim 1.6.12 problem. Looks like Nim 1.6.14 does not suffer from this bug.
I found this when try to compile fluffy with recent ssz-serialization.
nimbus-eth1 still not migrate to Nim 1.6.14 because of nim vm regression in 1.6.14. 
I think we should wait for 1.6.16 or later

**Comment by tersec** [comment] 2023-08-23 05:39
In which case it's not a `nim-ssz-serialization` bug. Reasonable to close this issue?

**Comment by arnetheduck** [comment] 2023-08-23 05:39
> In which case it's not a nim-ssz-serialization bug. Reasonable to close this issue?

if there's a simple / trivial workaround, I'd go for that

**Comment by tersec** [comment] 2023-08-23 05:48
> > In which case it's not a nim-ssz-serialization bug. Reasonable to close this issue?
> 
> if there's a simple / trivial workaround, I'd go for that

Well, as many of
either
- the "simple / trivial workaround" doesn't reduce the code quality or create strange-looking code which has to be explained and wondered about/around indefinitely, i.e. if the workaround is just better, or at least neutral, and creates negligible risk; or

- explicit "TODO" for removal, linking to this issue, and mentioning in the codebase that it's a Nim 1.6.12 issue that Nim 1.6.14 doesn't have, so it is easy to find and remove when (not if) appropriate. For example, when `nimbus-eth1` updates to Nim 1.6.16.

Nimbus and associated libraries already have too many workarounds. Adding more creates maintenance costs for a language version which is only going to become less common (how many people are able to use 1.6.12 but not 1.6.14 yet?). These costs might be worthwhile, e.g., to facilitate `nimbus-eth1` development right now.

For example, the workaround removed in https://github.com/status-im/nimbus-eth2/pull/5219 years after it was introduced had been, in fact, fixed in upstream Nim and incorporated into Nimbus's vendored version within weeks after that, but because none of this was done in that case, it took disproportionately long to discover, reverse-engineer what precise failing scenario, test the removal, and remove. That's a failure mode I'd like to avoid, in general.

**Comment by arnetheduck** [comment] 2023-08-23 05:56
I think you're overthinking it a bit - ie fixing a problem like this usually boils down to something like a mixin, bind or simply reordering the code a little so that the compiler can find the function during instantiation - there is 0 maintenance cost once you've introduced the fix and the only reason you consider it a "workaround" is the path that brought us here, ie a bug report - this can also be seen in that the removal of _most_ workarounds tends to be underwhelming it terms of what it achieves in terms of code real estate or hacks: they change some minor detail in a some minor function but rarely have any effect beyond that, unless the issue is truly egregious.

Also, the objective of a bug report is to solve the issue and there might be multiple ways of doing that: fixing the library, upgrading the compiler etc - since 1.6.14 has other problems / bugs, it becomes a tradeoff between the various bugs and sometimes, the fix is _really simple_ on this side of the problem meaning we should go for it.

**Closed** 2023-08-23 10:49 UTC
